export const SET_CURRENT_DATE = "BLOG/SINGLE_DATE_PAGE/SET_CURRENT_DATE";
export const SET_CURRENT_PAGE = "BLOG/SINGLE_DATE_PAGE/SET_CURRENT_PAGE";
export const SET_CURRENT_PAGI = "BLOG/SINGLE_DATE_PAGE/SET_CURRENT_PAGI";