export const SET_CURRENT_PAGE = "BLOG/CATEGORY/SET_CURRENT_PAGE";
export const SET_CURRENT_PAGI = "BLOG/CATEGORY/SET_CURRENT_PAGI";
export const SET_CURRENT_CATEGORY = "BLOG/CATEGORY/SET_CURRENT_CATEGORY";