export const SET_CURRENT_CATEGORY = "BLOG/SINGLE_CATEGORY/SET_CURRENT_CATEGORY";
export const SET_CURRENT_PAGE = "BLOG/SINGLE_CATEGORY/SET_CURRENT_PAGE";
export const SET_CURRENT_PAGI = "BLOG/SINGLE_CATEGORY/SET_CURRENT_PAGI";