export const Home = Object.freeze({
    SET_MAINPOST_ARR_ID: "BLOG/STATUSES/HOME/SET_MAINPOST_ARR_ID",
    SHOW_COMMENTS: "BLOG/STATUSES/HOME/SHOW_COMMENTS",
    HIDE_COMMENTS: "BLOG/STATUSES/HOME/HIDE_COMMENTS",
    TOGGLE_COMMENTS: "BLOG/STATUSES/HOME/TOGGLE_COMMENTS",
    TOGGLE_FULLPOST: "BLOG/STATUSES/HOME/TOGGLE_FULLPOST",
    SET_CURRENT_PAGE: "BLOG/STATUSES/HOME/SET_CURRENT_PAGE",
    SET_CURRENT_PAGI: "BLOG/STATUSES/HOME/SET_CURRENT_PAGI"
});

export const Category = Object.freeze({
    SET_CURRENT_PAGE: "BLOG/STATUSES/CATEGORY/SET_CURRENT_PAGE",
    SET_CURRENT_PAGI: "BLOG/STATUSES/CATEGORY/SET_CURRENT_PAGI"
});

export const Location = Object.freeze({
    SET_LOCATION: "BLOG/LOCATION/SET_LOCATION"
});


