export const Home = Object.freeze({
    SET_MAINPOST_ARR_ID: "BLOG/HOME/SET_MAINPOST_ARR_ID",
    SHOW_COMMENTS: "BLOG/HOME/FUNC/SHOW_COMMENTS",
    HIDE_COMMENTS: "BLOG/HOME/FUNC/HIDE_COMMENTS",
    TOGGLE_COMMENTS: "BLOG/HOME/FUNC/TOGGLE_COMMENTS",
    TOGGLE_FULLPOST: "BLOG/HOME/FUNC/TOGGLE_FULLPOST"
});

export const Location = Object.freeze({
    SET_LOCATION: "BLOG/LOCATION/SET_LOCATION"
});


