export const SHOW_COMMENTS = "BLOG/HOME/FUNC/SHOW_COMMENTS";
export const HIDE_COMMENTS = "BLOG/HOME/FUNC/HIDE_COMMENTS";
export const TOGGLE_COMMENTS = "BLOG/HOME/FUNC/TOGGLE_COMMENTS";

export const TOGGLE_FULLPOST = "BLOG/HOME/FUNC/TOGGLE_FULLPOST";