export const SET_CURRENT_AUTHOR = "BLOG/AUTHOR_PAGE/SET_CURRENT_AUTHOR";
export const SET_CURRENT_PAGE = "BLOG/AUTHOR_PAGE/SET_CURRENT_PAGE";
export const SET_CURRENT_PAGI = "BLOG/AUTHOR_PAGE/SET_CURRENT_PAGI";

export const SET_AUTHOR_PAGE_DATA_READY = "BLOG/AUTHOR_PAGE/SET_AUTHOR_PAGE_DATA_READY";