export const SET_CURRENT_AUTHOR = "BLOG/AUTHOR_PAGE/SET_CURRENT_AUTHOR";
export const SET_CURRENT_PAGE = "BLOG/AUTHOR_PAGE/SET_CURRENT_PAGE";
export const SET_CURRENT_PAGI = "BLOG/AUTHOR_PAGE/SET_CURRENT_PAGI";