export const SET_CURRENT_TAG = "BLOG/SINGLE_TAG_PAGE/SET_CURRENT_TAG";
export const SET_CURRENT_PAGE = "BLOG/SINGLE_TAG_PAGE/SET_CURRENT_PAGE";
export const SET_CURRENT_PAGI = "BLOG/SINGLE_TAG_PAGE/SET_CURRENT_PAGI";