export const SET_CURRENT_SINGLE_POST = "BLOG/SINGLE_POST/SET_CURRENT_SINGLE_POST";
export const SHOW_COMMENTS = "BLOG/SINGLE_POST/SHOW_COMMENTS";
export const HIDE_COMMENTS = "BLOG/SINGLE_POST/HIDE_COMMENTS";

export const SINGLE_POST_DATA_READY = "BLOG/SINGLE_POST/DATA_READY";


