export const  SHOW_COMMENTS = "BLOG/HOME/SHOW_COMMENTS";
export const  HIDE_COMMENTS = "BLOG/HOME/HIDE_COMMENTS";
export const  TOGGLE_COMMENTS = "BLOG/HOME/TOGGLE_COMMENTS";
export const  TOGGLE_FULLPOST = "BLOG/HOME/TOGGLE_FULLPOST";
export const  SET_CURRENT_PAGE = "BLOG/HOME/SET_CURRENT_PAGE";
export const  SET_CURRENT_PAGI = "BLOG/HOME/SET_CURRENT_PAGI";

export const SET_MAIN_POST = "BLOG/HOME/SET_MAIN_POST";